name: Android & Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x]

        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Yarn Install, (Test)
              run: |
                  yarn

            - name: Build with Gradle
              run: yarn build

            - name: Publish Release APK
              # uses: siristechnology/action-release@master
              env:
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
                  RELEASE_FILE_PATH: android/app/build/outputs/apk/release/app-release.apk
                  RELEASE_TITLE: 'New Build'
