name: Publish Release APK
on:
 push:
  branches:
   - master

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@master
   - name: Publish Release APK
     uses: siristechnology/action-release-react-native-apk@master
     env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
      APP_FOLDER: android/app
      RELEASE_TITLE: "New Build"
